FROM almalinux:9
# CMD ["ping", "google.com"]
CMD ["google.com"]
ENTRYPOINT ["ping"]
# during docker run, it will ping google.com unless another input is provided at run time.
# if yahoo.com is passed as input during run time, it will ping yahoo.com replacing google.com